# Generated by Django 2.2 on 2020-11-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='created_by',
            new_name='technician',
        ),
    ]
